project:
  type: website
  output-dir: docs
website:
  title: "Colloque GEOAI 2025"
  page-navigation: false
  navbar:
     
    left:
      - text: "Accueil"
        href: index.qmd
      - text: "Appel à communication"
        href: appel.qmd
      - text: "Comité scientifique"
        href: comite.qmd
      - text: "Comité d'organisation"
        href: com_org.qmd
      - text: "Programme"
        href: programme.qmd
      
  page-footer: "© 2025 - GEOAI, Kaolack, Sénégal "
  margin-header: |
    ![](/img/ussein.png)

format:
  html:
    page-layout: full
    theme: lumen
    css: styles.css
    toc: true
