
---
title: "Comité d'organisation"
format: html
---

# Comite d'organisation

- Président : Dr Labaly TOURE, Labaly.toure@ussein.edu.sn, 77 577 32 08
- Rapporteurs : Dr Pape Ngore Sarr SADIO, 
                            Dr Moussa SOW
 sawrou.fall@ussein.edu.sn 773350157

**Commission Logistique, Transport et Technique**

- Président : M. DIAMANKA
- M Sémou NDIAYE
- M. SAER
- M. BOURANG
- M. DEME
- Mme ASSA KAMARA
- M. CODE
- Mme ADJI MARI
- M. GUIRO
- M. LAMINE MBAYE
- M. OUMAR DIOUF
- M. BIRAHIM MBAYE
- M. MOHAMED MBAYE

**Commission Communication et Médias**


- Président : M. GOUDIABY
- Dr Pape Ngore SADIO
- M. KARALAN SY
- M. HUGUES PECOUT
- M. NGAGNE THIOUB
- M. MOHAMED GAYE
- M. El Hadj Malick NIANG
- M. PASCAL FAYE
- M. GRÉGOIRE
- Dr Ousseynou Ba oussseynou.ba@ussein.edu.sn 774476519

**Commission Partenariats et Financement**

- Présidente : Mme FATOU GUEYE
- M. MAMADOU AMADOU LY
- M. DJIBY MBENGUE
- Mme DIOP
- Mme KPARE
- CSA DIEDHIOU
- M. DIARRA
- Mme Pauline Gluski

**Commission Hébergement, Restauration**

- Présidente : Mme OUMOU KEITA
- Mme FATOU DIOUF
- Mme NDEYE NDOUMBE SECK
- Mme THIOMBANE
- Pr SYLLA
- M. Djiby DIOP

**Secrétariat du Colloque**
- Présidente : Mme KANDJI
- Mme BOCOUM
- Mme Awa Diop
- Secrétaires USSEIN
